### ISSUE TITLE
Opencivicdata migration checklist

### ISSUE THREAD

**Issue by fgregg** [datamade/chi-councilmatic#249]
- [ ] mayor is not member of council so his role does not show in list of sponsors http://127.0.0.1:8000/legislation/o2018-8860/
- [ ] add order_by to meta class on EventAgendaItem https://github.com/opencivicdata/python-opencivicdata/blob/master/opencivicdata/legislative/models/event.py
- [ ] import data command for shapes
- [ ] use signal handler to kick off update_index

**Comment by fgregg** [comment]
moved this checklist to this PR https://github.com/datamade/django-councilmatic/pull/240
